version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://admin:041013@db:5432/testing_platform
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - ./reports:/app/reports
      - ./static:/app/static

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=testing_platform
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=041013
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: