"""add email field to users

Revision ID: 1e86e47dd906
Revises: cc8b887dca8a
Create Date: 2025-10-24 15:59:55.843021

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1e86e47dd906'
down_revision = 'cc8b887dca8a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userinfo', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.drop_index('email', table_name='userinfo')
    op.create_index(op.f('ix_userinfo_email'), 'userinfo', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userinfo_email'), table_name='userinfo')
    op.create_index('email', 'userinfo', ['email'], unique=False)
    op.alter_column('userinfo', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###