"""add password_hash to userinfo

Revision ID: 570701d8da4c
Revises: 1e86e47dd906
Create Date: 2025-10-24 16:32:40.383635

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '570701d8da4c'
down_revision = '1e86e47dd906'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userinfo', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.alter_column('userinfo', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_column('userinfo', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userinfo', sa.Column('hashed_password', mysql.VARCHAR(length=255), nullable=False))
    op.alter_column('userinfo', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.drop_column('userinfo', 'password_hash')
    # ### end Alembic commands ###