"""Initial migration

Revision ID: 67807bca625d
Revises: 
Create Date: 2025-10-17 14:05:12.790552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67807bca625d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###