"""Initial migration for MySQL

Revision ID: cc8b887dca8a
Revises: 
Create Date: 2025-10-24 11:25:08.551889

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import JSON, Column

# revision identifiers, used by Alembic.
revision = 'cc8b887dca8a'
down_revision = None
branch_labels = None
depends_on = None
headers=Column(JSON)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('avatar_path', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userinfo_id'), 'userinfo', ['id'], unique=False)
    op.create_index(op.f('ix_userinfo_username'), 'userinfo', ['username'], unique=True)
    op.create_table('projectinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=100), nullable=False),
    sa.Column('test_style', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['userinfo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projectinfo_id'), 'projectinfo', ['id'], unique=False)
    op.create_table('apiinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_name', sa.String(length=100), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('body', sa.JSON(), nullable=True),
    sa.Column('expected_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projectinfo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apiinfo_id'), 'apiinfo', ['id'], unique=False)
    op.create_table('business_flow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flow_name', sa.String(length=100), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('test_type', sa.String(length=20), nullable=True),
    sa.Column('case_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projectinfo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_flow_id'), 'business_flow', ['id'], unique=False)
    op.create_table('test_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_name', sa.String(length=100), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('test_type', sa.String(length=20), nullable=True),
    sa.Column('report_path', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projectinfo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_reports_id'), 'test_reports', ['id'], unique=False)
    op.create_table('uiinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_name', sa.String(length=100), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('script_content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projectinfo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uiinfo_id'), 'uiinfo', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uiinfo_id'), table_name='uiinfo')
    op.drop_table('uiinfo')
    op.drop_index(op.f('ix_test_reports_id'), table_name='test_reports')
    op.drop_table('test_reports')
    op.drop_index(op.f('ix_business_flow_id'), table_name='business_flow')
    op.drop_table('business_flow')
    op.drop_index(op.f('ix_apiinfo_id'), table_name='apiinfo')
    op.drop_table('apiinfo')
    op.drop_index(op.f('ix_projectinfo_id'), table_name='projectinfo')
    op.drop_table('projectinfo')
    op.drop_index(op.f('ix_userinfo_username'), table_name='userinfo')
    op.drop_index(op.f('ix_userinfo_id'), table_name='userinfo')
    op.drop_table('userinfo')
    # ### end Alembic commands ###